# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7930402f34e1765c31d5621e2db4297e6bed9a483089dd46155fde4f80ead487c79ccb600d9e1c0b575e4f21f81d6b619aeb0d548c67aca3b2cceb53269c872

test:
  secret_key_base: c6da509597761d6707f58fd80273d9d6184ea9d4e09ee4d4c266d766b83cade775117f18e4d984b4f5bd366e739affd1c9d14d2fc2c674fb819a5f260a0dbf5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
